---
CSR-1:
  hostname: 172.20.58.31
  username: admin
  password: cisco
  platform: cisco_ios

CSR-2:
  hostname: 172.20.58.32
  username: admin
  password: cisco
  platform: cisco_ios

CSR-3:
  hostname: 172.20.58.33
  username: admin
  password: cisco
  platform: cisco_ios
